#!/usr/bin/env python3
"""Fresh NON-CONSTRUCTED corpus — phase 1 (n=12), the generalization test bed (EXPLORATORY).

Everything so far was validated on ONE constructed set: 8 mined-out problems, flaws WE injected. This
builds the opposite — fresh problems run through the REAL produce->revise pipeline to yield NATURAL
(R0, R1) pairs with no planted flaws. Whatever flaws appear are what the producer/reviser actually does.
The validated ruler + gate + loop + an independent panel get applied to THESE (next step), to see whether
the architecture generalizes past the hothouse.

Design (Bart's calls):
  * HYBRID source: 3 hand-authored anchors in FRESH domains (not among the original 8) + 9 problems
    generated by GPT-5.2 (a different vendor than the Claude producer/ruler — breaks the monoculture),
    one per distinct domain seed to force diversity. Generation is blind to the architecture.
  * START AT 12, validate the pipeline + eyeball natural-pair quality before scaling to 24/50.
  * (Ground truth = independent model panel — built in the NEXT script, not here.)

Anchors are realistic-but-authored pending Bart's real decisions — swap them in at scale-up.

Pipeline per problem: produce R0 (Claude solve) -> one natural challenge (GPT, cross-vendor) ->
revise to R1 (Claude). Reuses run_study's CHAL/PROD prompts so R1 is the genuine single-challenge
revision — the exact thing the paper covers and the loop iterates PAST. Resumable. Writes
analysis/natural-corpus.json.

Usage: python3 build_natural_corpus.py
Env: ANTHROPIC_API_KEY, OPENAI_API_KEY (falls back to Claude generation if GPT errors).
"""
import json, concurrent.futures as cf
import run_study as R
import lib_llm as L

OUT_JSON = R.PILOT / "analysis" / "natural-corpus.json"

# --- 3 hand-authored anchors, FRESH domains (distinct from the original 8) ---
ANCHORS = [
    {"id": "P-nat-anchor-radiology", "domain": "healthcare operations", "source": "anchor(authored)",
     "problem": (
        "A 400-bed regional hospital network currently outsources all overnight (11pm-7am) radiology reads to "
        "a teleradiology vendor at $38/study, ~9,000 overnight studies/year. The vendor's contract renews in 6 "
        "months with a proposed 22% rate increase. Median read turnaround is 41 minutes against a 30-minute SLA "
        "the ED chief says is now routinely missed on strokes and traumas, where minutes change outcomes and "
        "liability. Options: (a) bring overnight reads in-house by hiring 3 nocturnist radiologists (fully-loaded "
        "~$520k each, 4-6 month recruit in a tight market, hard to staff 365 nights with 3 FTEs); (b) renew with "
        "the incumbent but pay for a premium 20-minute-SLA tier (+31% on rate); (c) split — in-house the "
        "stroke/trauma subset (~15% of volume) and keep routine overnight reads outsourced. Malpractice carrier "
        "signals a premium change either way. Recommend the staffing/sourcing model for overnight reads.")},
    {"id": "P-nat-anchor-storage", "domain": "energy / utility planning", "source": "anchor(authored)",
     "problem": (
        "A municipal utility serving 210,000 meters faces a projected 45 MW summer peak-capacity shortfall in 3 "
        "years, and a state mandate to cut generation carbon 40% by year 5 with penalties for missing it. The "
        "afternoon peak is ~90 minutes long. Options: (a) a 40 MW / 160 MWh lithium battery ($58M capex, ~14-month "
        "interconnect queue, degrades ~2.5%/yr, qualifies for a 30% federal tax credit expiring in 2 years); (b) a "
        "50 MW dual-fuel peaker ($41M, faster to build, but adds carbon and risks the mandate penalty); (c) a "
        "demand-response program (target 35 MW curtailable, ~$12M to stand up, but historical realized curtailment "
        "is only 55-70% of enrolled load and erodes as customers opt out). Interest rates are up 250 bps, straining "
        "the utility's debt capacity. Recommend how to close the capacity shortfall while meeting the carbon mandate.")},
    {"id": "P-nat-anchor-fedramp", "domain": "SaaS compliance / go-to-market", "source": "anchor(authored)",
     "problem": (
        "A 140-person B2B SaaS company has a $4.2M/yr federal agency deal contingent on FedRAMP Moderate "
        "authorization, which the agency wants in place within 12 months. The product runs multi-tenant on "
        "commercial AWS. Options: (a) build a separate single-tenant GovCloud environment and pursue FedRAMP "
        "directly (est. $1.8-2.5M, 12-18 months typical, needs a sponsoring agency and a 3PAO, diverts ~6 "
        "engineers); (b) resell through an already-authorized FedRAMP platform/partner (revenue share ~25%, live "
        "in ~4 months, but cedes the roadmap and data-plane control); (c) decline the federal deal for now and "
        "revisit after the next funding round. The company has 14 months of runway and its commercial roadmap is "
        "already behind. Recommend the path to (or away from) the federal market.")},
]

DOMAIN_SEEDS = [
    "public-sector policy / municipal budgeting", "industrial manufacturing / plant operations",
    "retail & e-commerce fulfillment", "digital media / subscription business",
    "agriculture & food supply chain", "higher education administration",
    "urban transportation / mobility", "clinical trial / biotech development",
    "commercial insurance / risk underwriting",
]

GEN_SYS = (
    "You design hard, realistic decision problems used to stress-test expert recommendations. Produce ONE "
    "consequential decision problem in the given domain: a specific situation where a decision-maker must "
    "choose among a few concrete options (label them (a)/(b)/(c)) under real constraints. Include concrete "
    "numbers, constraints, deadlines, and tradeoffs so a recommendation could be materially right or wrong. "
    "Exactly one decision must be made and stated as the ask. Do NOT provide an answer, hint at one, or "
    "mention evaluation, flaws, or testing. 130-220 words, realistic and specific."
)
GEN_USER = "DOMAIN: {domain}\n\nReturn JSON: {{\"domain\": str, \"problem\": str}}"

SOLVE_SYS = (
    "You are a senior expert. Produce a crisp, shippable recommendation for the hard decision problem below: "
    "make the actual decision (pick an option), justify it against the binding constraints and tradeoffs, and "
    "state the load-bearing assumptions it hinges on. Keep it tight and decision-grade, not an essay."
)
SOLVE_USER = "PROBLEM:\n{problem}\n\nReturn JSON: {{\"recommendation\": str}}"


def gen_problem(seed, idx):
    uid = f"nat_gen__{idx:02d}"
    cached = R.load(uid)
    if cached:
        return cached
    vendor = "gpt"
    try:
        out = L.gpt_json(R.GPT, GEN_SYS, GEN_USER.format(domain=seed), max_completion_tokens=4000)
        prob = out.get("problem", "") if isinstance(out, dict) else ""
        if not prob or len(prob) < 200:
            raise ValueError("gpt gen too short/empty")
    except Exception as e:   # noqa: BLE001
        print(f"[corpus] gen {idx} GPT failed ({repr(e)[:80]}); Claude fallback", flush=True)
        out = L.claude_json(R.CLAUDE, GEN_SYS, GEN_USER.format(domain=seed), max_tokens=2000, temperature=0.9)
        prob = out.get("problem", "") if isinstance(out, dict) else ""
        vendor = "claude(fallback)"
    rec = {"id": f"P-nat-gen-{idx:02d}", "domain": seed, "source": f"generated({vendor})", "problem": prob}
    R.save(uid, rec)
    return rec


def produce_r0(prob):
    uid = f"nat_solve__{prob['id']}"
    cached = R.load(uid)
    if cached:
        return cached["r0"]
    out = L.claude_json(R.CLAUDE, SOLVE_SYS, SOLVE_USER.format(problem=prob["problem"]), max_tokens=6000, temperature=0.7)
    r0 = (out.get("recommendation", "") if isinstance(out, dict) else "") or ""
    R.save(uid, {"r0": r0})
    return r0


def produce_r1(prob, r0):
    """One natural challenge (GPT, cross-vendor) -> Claude revision. Returns (r1, meta)."""
    cu = f"nat_chal__{prob['id']}"
    chal = R.load(cu)
    if not chal:
        chal = R.challenger_call("gpt", R.CHAL_SYS, R.CHAL_R1_USER.format(problem=prob["problem"], rec=r0))
        R.save(cu, chal)
    objs = chal.get("objections", []) if isinstance(chal, dict) else []
    ru = f"nat_rev__{prob['id']}"
    rev = R.load(ru)
    if not rev:
        rev = L.claude_json(R.CLAUDE, R.PROD_SYS,
                            R.PROD_USER.format(problem=prob["problem"], rec=r0, obj=R.fmt_objections(objs)),
                            max_tokens=6000, temperature=0.7)
        R.save(ru, rev)
    r1 = (rev.get("revised_recommendation", "") if isinstance(rev, dict) else "") or ""
    return r1, {"n_objections": len(objs), "material_remaining": chal.get("material_objections_remaining"),
                "accept_as_final": rev.get("accept_as_final"),
                "dispositions": rev.get("dispositions", [])}


def main():
    # 1. assemble the 12 problems (anchors + generated)
    problems = list(ANCHORS)
    gen = [None] * len(DOMAIN_SEEDS)
    with cf.ThreadPoolExecutor(max_workers=R.WORKERS) as ex:
        futs = {ex.submit(gen_problem, s, i + 1): i for i, s in enumerate(DOMAIN_SEEDS)}
        for f in cf.as_completed(futs):
            gen[futs[f]] = f.result()
    problems += [g for g in gen if g]
    print(f"[corpus] {len(problems)} problems ({len(ANCHORS)} anchors + {len(problems)-len(ANCHORS)} generated)", flush=True)

    # 2. produce R0 then R1 for each (per-problem chain; problems concurrent)
    def build(prob):
        r0 = produce_r0(prob)
        r1, meta = produce_r1(prob, r0)
        return {**prob, "R0": r0, "R1": r1, **meta}
    rows = []
    with cf.ThreadPoolExecutor(max_workers=R.WORKERS) as ex:
        futs = {ex.submit(build, p): p["id"] for p in problems}
        for f in cf.as_completed(futs):
            try:
                rows.append(f.result())
            except Exception as e:   # noqa: BLE001
                print(f"[corpus] ERROR {futs[f]}: {repr(e)[:140]}", flush=True)
    rows.sort(key=lambda r: r["id"])

    summary = {"EXPLORATORY": True, "phase": 1, "n": len(rows),
               "note": "natural (R0,R1) pairs, no planted flaws; anchors authored pending Bart's real decisions",
               "problems": rows}
    OUT_JSON.write_text(json.dumps(summary, indent=2))

    print("\n=== NATURAL CORPUS (phase 1) — quality eyeball ===")
    print(f"  {'id':22s} {'source':20s} {'R0w':>5s} {'R1w':>5s} {'obj':>4s} {'chg%':>5s} accept")
    for r in rows:
        r0w, r1w = len(r["R0"].split()), len(r["R1"].split())
        # crude change signal: word-set jaccard distance R0 vs R1
        a, b = set(r["R0"].split()), set(r["R1"].split())
        chg = 100 * (1 - len(a & b) / max(1, len(a | b)))
        flag = "" if (r0w > 60 and r1w > 60) else "  <-- THIN, check"
        print(f"  {r['id']:22s} {r['source']:20s} {r0w:5d} {r1w:5d} {r['n_objections']:4d} {chg:4.0f}% "
              f"{str(r['accept_as_final']):5s}{flag}")
    print(f"\nwrote {OUT_JSON.relative_to(R.PILOT)}  (n={len(rows)})")


if __name__ == "__main__":
    main()
